# Name of the project
PROJECT_NAME = Project

#Doxyfile folder
DOC = documentation

#All source code files
SRC = bus.c\
src/project_operations.c

#All test source files
TEST_SRC = src/project_operations.c\
test/test_project_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = bus.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Bulid:
	gcc function1.c test_bus.c unity/unity.c -Iunity
Run:
	./a.out
	
